AWSTemplateFormatVersion: '2010-09-09'
Description: Stack principal do desafio CloudFormation - cria EC2 + S3 + Security Group

Parameters:
  InstanceType:
    Description: Tipo de instância EC2
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  MeuBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: meu-primeiro-bucket-cloudformation-exemplo

  MeuSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir SSH e HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MinhaInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (us-east-1)
      SecurityGroups:
        - Ref: MeuSecurityGroup
      Tags:
        - Key: Name
          Value: MinhaPrimeiraInstanciaCloudFormation

Outputs:
  BucketName:
    Description: Nome do bucket S3 criado
    Value: !Ref MeuBucketS3

  EC2InstanceId:
    Description: ID da instância EC2 criada
    Value: !Ref MinhaInstanciaEC2

  SecurityGroupId:
    Description: ID do Security Group criado
    Value: !Ref MeuSecurityGroup
